"""deleted column on table projects

Revision ID: b3d43af57b27
Revises: fec04bc78733
Create Date: 2023-09-05 16:19:25.275954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d43af57b27'
down_revision = 'fec04bc78733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('publication_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
