"""deleted column on table blogs

Revision ID: fec04bc78733
Revises: 0c76226e0254
Create Date: 2023-09-05 16:15:28.645152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec04bc78733'
down_revision = '0c76226e0254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('publication_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
